services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "${CLIENT_PORT}:80"
